services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    volumes:
      - ./mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://${MONGO_USERNAME:-root}:${MONGO_PASSWORD:-password}@mongodb:27017/forms
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME:-root}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD:-password}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-password}
